name: rememberme
description: "RememberMe - Dementia Prevention Lifestyle Tracker by Lucy Cavendish College, University of Cambridge"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.6.1
  
  # State Management
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  
  # Charts and Data Visualization
  fl_chart: ^0.69.0
  
  # Date and Time
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  
  # Local Storage
  sqflite: ^2.4.1
  path: ^1.9.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # Health and Fitness
  # health: ^10.1.0  # Temporarily disabled due to compatibility issues
  pedometer: ^4.0.2
  
  # Forms and Validation
  flutter_form_builder: ^10.2.0
  
  # HTTP and API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Image Handling
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Animations
  lottie: ^3.1.2
  animations: ^2.0.11
  
  # Utilities
  uuid: ^4.5.0
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  
  # App Icon Generation
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/animations/

# fonts:
#   - family: Inter
#     fonts:
#       - asset: assets/fonts/Inter-Regular.ttf
#       - asset: assets/fonts/Inter-Medium.ttf
#         weight: 500
#       - asset: assets/fonts/Inter-SemiBold.ttf
#         weight: 600
#       - asset: assets/fonts/Inter-Bold.ttf
#         weight: 700

# App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
